% parameters for processing Kelvin Hughes coherent X-Band RADAR scans
clear
close all

datestring = '20170919\20\';
datapath = ['R:\' datestring];
scanpath =  ['R:\' datestring];
framepath = ['R:\' datestring 'frames\'];
wavepath =  ['R:\' datestring 'waves\'];
magavgpath = ['R:\' datestring 'mag_avg\'];
% mkdir(framepath);
mkdir(wavepath);
% mkdir(magavgpath);

xlen = 256;                    % number of spatial (x,y) points
ylen = 256;
tlen = 32;                      % number of time (t) points (RADAR scans)
rbox = 5000;                    % starting range from RADAR to front edge of box (m)
thetabox = 288;                 % starting angle from RADAR to middle front edge of box (degrees true)
dthetabox = 10;                 % additional box rotation once in place
h = 35;                         % ocean depth (m)
g = 9.8;                        % gravity, m/s^2
sol = 3e8;                      % speed of light, m/s
ploton = 1;                     % 1=enable/0=disable plotting
Ts = 60/10;                     % RADAR scan period (s), 10 RPM or 20 RPM
wcutoff = 0.16;                 % radian frequency lower cutoff (rad/s), throw away data below this
kcutoff_low = 0.01;            % wavenumber lower cutoff (rad/m), throw away data below this
kcutoff_hi = 0.22;              % wavenumber higher cutoff, throw away data above this
cmax = 3;                       % maximum current velocity toward RADAR, used to limit search for the dispersive energy
Hs = 1.5;                      % significant wave height, used to scale surface wave results
HL_offset = 202.5;              % degrees, heading line offset relative to the bow
% dh = 13.45;
% dh = 15;                        % degrees, additional heading offset from ship GPS origin, used in determining exact lat/lon of the radar tower
% df = 14;
% df = 25;                      % m forward, forward offset from ship GPS origin
% ds = 3.35;                      % m starboard, starboard offset from ship GPS origin
rres = 3.75;                    % range resolution (m)

% 10 transmit frequency pairs (GHz), KH pair numbers 16-25, renumbered 1-10 here
f_table = [9.23, 9.35;...   %16
           9.23, 9.39;...   %17
           9.23, 9.43;...   %18
           9.23, 9.47;...   %19
           9.27, 9.39;...   %20
           9.27, 9.43;...   %21
           9.27, 9.47;...   %22
           9.31, 9.43;...   %23
           9.31, 9.47;...   %24
           9.35, 9.47];     %25
% select frequency pair here, it is not in any of the file/frame headers
findex = 10;
% F1 and F2 for Doppler calculations
txf1 = 1e9*(f_table(findex,1));
txf2 = 1e9*(f_table(findex,2));

% ranges and angles processed for Doppler
rmin=200; 
rmax=20000;              
azmin=240;
azmax=305;

% fixed radar location
khlongitude = -120.638028;
khlatitude = 34.882361; 

% pulse count maximums, determined by reading lots of files
% 10RPM = 7, 20RPM = 4
pulses_per_turning_12NM = 7;
pulses_per_range_mode_12NM = 2;
pulses_per_turning_24NM = 2;
pulses_per_range_mode_24NM = 3;
% haven't figured out 48NM mode yet

% set up data structures
talonheader = struct('modelnumber',[],...
                     'filename',[],...
                     'filesizemb1',[],...
                     'filesizesec',[],...
                     'timestamp',[],...
                     'reserved1',[],...
                     'buffersize',[],...
                     'datarate',[],...
                     'dataloss',[],...
                     'dataoffset1',[],...
                     'reserved2',[],...
                     'reserved3',[],...
                     'reserved4',[],...
                     'reserved5',[],...
                     'reserved6',[],...
                     'reserved7',[],...
                     'reserved8',[],...
                     'reserved9',[],...
                     'reserved10',[],...
                     'boardnumber',[],...
                     'reserved11',[],...
                     'reserved12',[],...
                     'reserved13',[],...
                     'reserved14',[],...
                     'channelnumber',[],...
                     'reserved15',[],...
                     'reserved16',[],...
                     'lastgooddatalocation',[],...
                     'reserved17',[],...
                     'gpslatitude',[],...
                     'gpslongitude',[],...
                     'gpsaltitude',[],...
                     'reserved18',[],...
                     'filesizemb2',[],...
                     'reserved19',[],...
                     'userdefined1',[],...
                     'userdefined2',[],...
                     'userdefined3',[],...
                     'userdefined4',[],...
                     'userdefined5',[],...
                     'userdefined6',[],...
                     'userdefined7',[],...
                     'userdefined8',[],...
                     'userdefined9',[],...
                     'userdefined10',[],...
                     'reserved20',[],...
                     'reserved21',[],...
                     'reserved22',[],...
                     'reserved23',[],...
                     'reserved24',[],...
                     'reserved25',[],...
                     'reserved26',[],...
                     'systemrevisionnumber',[],...
                     'reserved27',[],...
                     'protocol',[],...
                     'reserved28',[],...
                     'reserved29',[],...
                     'reserved30',[],...
                     'reserved31',[],...
                     'reserved32',[],...
                     'reserved33',[],...
                     'reserved34',[],...
                     'reserved35',[],...
                     'reserved36',[],...
                     'reserved37',[],...
                     'reserved38',[],...
                     'reserved39',[],...
                     'reserved40',[],...
                     'numberoffiles',[],...
                     'reserved41',[],...
                     'startfileindex',[],...
                     'dataoffset2',[]);
                     
fileheader=struct('filesync',[],...
                  'timesec',[],...
                  'timeusec',[],...
                  'fwid',[],...
                  'sampletime',[],...
                  'p1start',[],...
                  'p2start',[],...
                  'p3start',[],...
                  'fsamples',[],...
                  'p1recst',[],...
                  'p2recst',[],...
                  'p3recst',[],...
                  'recsamples',[],...
                  'p1f1rng0',[],...
                  'p2f1rng0',[],...
                  'p3f1rng0',[],...
                  'p1f2rng0',[],...
                  'p2f2rng0',[],...
                  'p3f2rng0',[],...
                  'videoorder',[],...
                  'p1vidsmpls',[],...
                  'p2vidsmpls',[],...
                  'p3vidsmpls',[],...
                  'reserved1',[],...
                  'reserved2',[],...
                  'reserved3',[],...
                  'reserved4',[],...
                  'reserved5',[],...
                  'reserved6',[],...
                  'reserved7',[],...
                  'reserved8',[],...
                  'reserved9',[]);
          
frameheader=struct('framesync',[],...
                   'frtimesec',[],...
                   'frtimeusec',[],...
                   'lastsmpls',[],...
                   'turning',[],...
                   'reserved1',[],...
                   'reserved2',[],...
                   'reserved3',[]);
frameheaderlen = 8; % 32 bit words

% file constants
FILESYNC = uint32(hex2dec('AA550001'));
F1TURNING = uint32(hex2dec('0000FFFF'));
F2TURNING = uint32(hex2dec('FFFF0000'));
FRAMESYNC = uint32(hex2dec('55AA0001'));
PHASE = uint32(hex2dec('00007FFF'));
SIGNBIT = uint16(hex2dec('8000'));
MAGNITUDE = uint32(hex2dec('FFFF8000'));
MAX = uint32(hex2dec('FFFFFFFF'));

% save the parameters
save('parameters.mat', 'datapath',...
                       'scanpath',...
                       'framepath',...
                       'wavepath',...
                       'magavgpath',...
                       'xlen',...
                       'ylen',...
                       'tlen',...
                       'rbox',...
                       'thetabox',...
                       'dthetabox',...
                       'h',...
                       'g',...
                       'sol',...
                       'ploton',...
                       'Ts',...
                       'wcutoff',...
                       'kcutoff_low',...
                       'kcutoff_hi',...
                       'cmax',...
                       'Hs',...
                       'HL_offset',...
                       'rres',...
                       'txf1',...
                       'txf2',...
                       'rmin',...
                       'rmax',...
                       'azmin',...
                       'azmax',...
                       'khlongitude',...
                       'khlatitude',...
                       'pulses_per_turning_12NM',...
                       'pulses_per_range_mode_12NM',...
                       'pulses_per_turning_24NM',...
                       'pulses_per_range_mode_24NM',...
                       'talonheader',...
                       'fileheader',...
                       'frameheader',...
                       'frameheaderlen',...
                       'FILESYNC',...
                       'F1TURNING',...
                       'F2TURNING',...
                       'FRAMESYNC',...
                       'PHASE',...
                       'SIGNBIT',...
                       'MAGNITUDE',...
                       'MAX');